version: '2.1'

services:
  kpow:
    image: factorhouse/kpow-ce:latest
    hostname: kpow
    container_name: kpow
    networks:
      - kafka
    restart: unless-stopped
    ports:
      - "3010:3000"
    env_file:
      - resources/local-community.env
    mem_limit: 2G

networks:
  kafka:
    external: true
