---
version: '3'
services:

  kafka-ui:
    hostname: kafka-ui
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    networks:
      - kafka          
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA

networks:
  kafka:
    external: true