version: "3.5"

services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:latest
    restart: unless-stopped
    depends_on:
      - "victoriametrics"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - vm_net
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    restart: unless-stopped
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    networks:
      - vm_net
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: unless-stopped    
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - vm_net
    restart: always
volumes:
  vmagentdata: {}
  vmdata: {}
  grafana_data: {}
    
networks: 
  vm_net: ~