---
version: "3"
services:

  kafka-1:
    image: confluentinc/cp-kafka:7.6.0
#    profiles: ["broker", "all"]
    hostname: kafka-cp-1
    container_name: kafka-cp-1
    networks:
      - kafka
    ports:
#      - "9092:9092"
      - "29181:9094"
      - "29104:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_INTERNAL:PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "LISTENER_INTERNAL://kafka-cp-1:9092,LISTENER_EXTERNAL://192.168.1.4:29181" # Required for brokers  
      KAFKA_INTER_BROKER_LISTENER_NAME: "LISTENER_INTERNAL"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-cp-1:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "LISTENER_CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Required when you are running with a single-node cluster
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"  
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      
      # JMX configuration
      # KAFKA_JMX_HOSTNAME: localhost
      KAFKA_JMX_PORT: 9101
networks:
  kafka:
    external: true
