---
version: '3'
services:
  
  kafka-1:
    image: 'bitnami/kafka:latest'
    hostname: kafka-1
    container_name: kafka-1
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=LISTENER_CONTROLLER      
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka-1:9092,LISTENER_EXTERNAL://192.168.1.4:9181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG_DIR="/tmp/kraft-combined-logs"
      - JMX_PORT=9101
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    networks:
      - kafka      
    ports:
      - "9191:9092"
      - "9181:9094"
      - "9171:9101"

  kafka-2:
    image: 'bitnami/kafka:latest'
    hostname: kafka-2
    container_name: kafka-2
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=LISTENER_CONTROLLER      
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL      
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka-2:9092,LISTENER_EXTERNAL://192.168.1.4:9281
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG_DIR="/tmp/kraft-combined-logs"
      - JMX_PORT=9101
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    networks:
      - kafka            
    ports:
      - "9291:9092"
      - "9281:9094"
      - "9271:9101"

  kafka-3:
    image: 'bitnami/kafka:latest'
    hostname: kafka-3
    container_name: kafka-3
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=LISTENER_CONTROLLER      
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL            
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka-3:9092,LISTENER_EXTERNAL://192.168.1.4:9381
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG_DIR="/tmp/kraft-combined-logs"
      - JMX_PORT=9101
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    networks:
      - kafka            
    ports:
      - "9391:9092"
      - "9381:9094"
      - "9371:9101"

networks:
  kafka:
    external: true