version: '3.3'
services:
    httpd:
        image: 'httpd:latest'
        container_name: my-apache-app
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        ports:
            - 8080:80
        volumes:        
            - httpd_config:/usr/local/apache2/conf/
            - httpd_data:/usr/local/apache2/htdocs/
        restart: unless-stopped
    filebrowser:
        image: hurlenko/filebrowser    
        container_name: filebrowser
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC        
            - FB_BASEURL=/f            
        ports:
            - 8081:8080
        volumes:
            - httpd_data:/data
            - /docker/filebrowser:/config
        restart: unless-stopped
volumes: 
  httpd_config: 
    driver: local
  httpd_data: 
    driver: local
