version: '3'
services:
  
  kafka-1:
    image: 'bitnami/kafka:latest'
    container_name: kafka-1
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=LISTENER_CONTROLLER      
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka-1:9092,LISTENER_EXTERNAL://192.168.1.4:9182
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    ports:
      - 9192:9092
      - 9182:9094

  kafka-2:
    image: 'bitnami/kafka:latest'
    container_name: kafka-2
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=LISTENER_CONTROLLER      
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL      
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka-2:9092,LISTENER_EXTERNAL://192.168.1.4:9183
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    ports:
      - 9193:9092
      - 9183:9094
      
  kafka-3:
    image: 'bitnami/kafka:latest'
    container_name: kafka-3
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENERS=LISTENER_INTERNAL://:9092,LISTENER_CONTROLLER://:9093,LISTENER_EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=LISTENER_CONTROLLER      
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL            
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka-3:9092,LISTENER_EXTERNAL://192.168.1.4:9184
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    ports:
      - 9194:9092
      - 9184:9094

  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA
